name: 投资助手

on:
  schedule:
    - cron: '30 1 * * *'
    - cron: '30 7 * * *'
    - cron: '30 13 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          pip install feedparser requests

      - name: 显示当前目录
        run: |
          pwd
          ls -la  # 查看当前目录及文件

      - name: 运行助手
        env:
          BARK_URL: ${{ secrets.BARK_URL }}
        run: |
          python collect_new.py  # 确保路径正确，文件在根目录
